version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
    ports:
      - "8123:8123"
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_data:/var/lib/clickhouse

  jupyter:
      build:
        context: .
        dockerfile: Dockerfile.jupyter
      ports:
        - "8888:8888"
      volumes:
        - ./notebooks:/home/jovyan/notebooks
        - ./data:/home/jovyan/data
      environment:
        - GRANT_SUDO=yes
        - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
        - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
        - CLICKHOUSE_DB=${CLICKHOUSE_DB}
        - CLICKHOUSE_USER=${CLICKHOUSE_USER}
        - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      depends_on:
        - clickhouse

volumes:
  clickhouse_data:
