FROM python:3.9-slim

WORKDIR /home/jovyan

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY data/ home/jovyan/data

EXPOSE 8888
CMD ["sh", "-c", "python3 data/load_data.py && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"]